<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://localhost:9080/axis/services/hello" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap"
	xmlns:impl="http://localhost:9080/axis/services/hello" xmlns:intf="http://localhost:9080/axis/services/hello" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!--WSDL created by Apache Axis version: 1.3
		Built on Oct 05, 2005 (05:23:37 EDT)-->

	<message name="getHelloResponse">

		<part name="getHelloReturn" type="soapenc:string" />

	</message>

	<message name="getHelloRequest">

		<part name="name" type="soapenc:string" />

	</message>

	<portType name="HelloService">

		<operation name="getHello" parameterOrder="name">

			<input message="impl:getHelloRequest" name="getHelloRequest" />

			<output message="impl:getHelloResponse" name="getHelloResponse" />

		</operation>

	</portType>

	<binding name="helloSoapBinding" type="impl:HelloService">

		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />

		<operation name="getHello">

			<wsdlsoap:operation soapAction="" />

			<input name="getHelloRequest">

				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.haa.c4j" use="encoded" />

			</input>

			<output name="getHelloResponse">

				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:9080/axis/services/hello" use="encoded" />

			</output>

		</operation>

	</binding>

	<service name="HelloServiceService">

		<port binding="impl:helloSoapBinding" name="hello">

			<wsdlsoap:address location="http://localhost:9080/axis/services/hello" />

		</port>

	</service>

</definitions>
