Insert into READER_RSS (rlink,rtitle,tags) values ('http://lengxiaohua.net/feed/','我们爱讲冷笑话','搞笑');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://blog.sina.com.cn/rss/1191258123.xml','韩寒','社会');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.feedsky.com/matrix67','Matrix67: My Blog','数学');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://mindhacks.cn/feed/','刘未鹏 | Mind Hacks','生活,思维,效率');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://lifesinger.org/blog/feed/','岁月如歌','编程,Javascript');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://forfuture1978.javaeye.com/rss','','搜索,Java');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.feedsky.com/chedong','车东[Blog^2]','搜索');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://ucdchina.com/rss/posts','最新文章 - UCD大社区','IT,技术');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://songshuhui.net/feed','科学松鼠会','科学');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://news.google.com/news?pz=1&cf=all&ned=cn&hl=zh-CN&topic=h&num=3&output=rss','焦点新闻 - Google 新闻','新闻,google');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://news.google.com/news?pz=1&cf=all&ned=cn&hl=zh-CN&topic=b&output=rss&num=20','财经 - Google 新闻','财经,google');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://money.163.com/special/00252EQ2/toutiaorss.xml','头条新闻-网易财经频道','网易头条');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://blog.sina.com.cn/rss/1195224593.xml','马艳丽','服装,马艳丽');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://moviegoer.cinepedia.cn/feed','moviegoer','电影,评论');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://blog.codingnow.com/index.xml','云风的 BLOG','IT,技术,云风');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.xiaohuayoumo.com/','笑话幽默百分百','笑话,幽默');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://yyecgongjie.blog.163.com/rss/','恒温理财','经济');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://huoding.com/feed','火丁笔记','编程,MySQL');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.feedsky.com/yeeyan-business','译言-商业/经济/营销','商业');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.feedsky.com/yeeyan-tech','译言-电脑/网络/数码科技','科技');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://www.36kr.com/feed','36氪','IT');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://www.geekonomics10000.com/feed','学而时嘻之','互联网,思维');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://zangxiankai.blog.sohu.com/rss','视觉思维之禅','UI,思维');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://www.tektalk.org/feed/','弯曲评论','技术,人物,潮流');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.feedsky.com/mlsx','Linux|系统管理|WEB开发','Web,Linux');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://timyang.net/feed/','Tim[后端技术]','Web,分布式,架构');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://www.cnbeta.com/backend.php','cnBeta.COM','IT,信息，新闻');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://blog.xiao3.info/feed','甜·咖啡','生活,感悟');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feeds.delicious.com/v2/rss/yycosammx?count=15','Delicious/yycosammx','计算机,技术');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feeds.delicious.com/v2/rss/zhoubaozhou?count=15','Delicious/zhoubaozhou','存储,分布式,高性能');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://blog.sina.com.cn/rss/1282300177.xml','张凯律师心灵对白','法律');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://www.bullock.cn/blogs/laoluo/Rss.aspx','皮赛罗可爱多---the peaceful side of luoyonghao','电影');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://vip-huangbo.blog.163.com/rss/','黄渤的博客','电影,明星');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.feedsky.com/jandannet','煎蛋','趣味');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feed.geli.me/','一个篱笆的遐想','生活');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feeds.feedsky.com/csdn.net/v_JULY_v','结构之法 算法之道','计算机,算法');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://feeds.feedsky.com/csdn.net/lee_eric','eric的专栏','IT,技术');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://sisopipo.com/blog/feed/','编程、生活、感悟','技术，生活，感悟');
Insert into READER_RSS (rlink,rtitle,tags) values ('http://sisopipo.com/rssreader/sinarss2.php?id=1940798632','总裁语录','管理,理念');
